

Wechat_ssh:
  host: 54.222.195.145
  user: admin
  keys: ~/.ssh/infra_stage-id_rsa
  database:
    host: stage-mysql-27.cdendvrkytps.rds.cn-north-1.amazonaws.com.cn
    remote_port: 3306
    local_port: 3306

Wechat_db:
  adapter: mysql2
  host: 127.0.0.1
  user: root
  password: tMq2OhtrF3afh1FL
  database: wechat_db

Wechat_http:
  base_uri: https://wechat-stage.student.com/wechat


Booking_ssh:
  host: 54.222.195.145
  user: admin
  keys: ~/.ssh/infra_stage-id_rsa
  database:
    host: stage-mysql-27.cdendvrkytps.rds.cn-north-1.amazonaws.com.cn
    remote_port: 3306
    local_port: 3306

Booking_db:
  adapter: mysql2
  host: 127.0.0.1
  user: root
  password: tMq2OhtrF3afh1FL
  database: wechat_db

Booking_http:
  base_uri: https://bookings.stage.overseasstudentliving.com
  basic_auth:
    user: oslqa
    password: m2WackNUHbAqHz51
  headers:
    Content-type: application/json
    X-OSL-PKEY: 32489878329jkkkjh3k4j2hjk324k
  shared_secret: 234kjkj324kjh23jk4h234jkhk23j4
